import "../../public/css/globals.css";
import "../../public/css/font.css";
import ReduxProvider from "./ReduxProvider";

export const metadata = {
  title: "Dubz login form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
